import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/app/navbar";
import {Theme, ThemePanel} from "@radix-ui/themes";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import "./theme-config.css"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme>
          <Navbar />
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
